// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    UserItem: typeof import('./src/components/user/UserItem.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
    Videos: typeof import('./src/components/video/Videos.vue')['default']
  }
}

export { }
